version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:12.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - data
    restart: unless-stopped

networks:
  data:
    driver: bridge

volumes:
    postgres:
